// PacketPreview: preview, edit, download, delete. "RealDoor never sends this for you."
"use client";

import { useState, useCallback } from "react";

interface PacketPreviewProps {
  ready: boolean;
  personName: string;
  announce: (message: string) => void;
  onDelete: () => void;
}

function generatePacketText(personName: string): string {
  return [
    "REALDOOR READINESS PACKET",
    "=========================",
    "",
    `Prepared for: ${personName}`,
    `Generated: ${new Date().toISOString().split("T")[0]}`,
    "",
    "This packet was prepared by the renter using RealDoor.",
    "RealDoor never sends this for you.",
    "A qualified person makes the decision.",
    "",
    "--- END ---",
  ].join("\n");
}

export default function PacketPreview({ ready, personName, announce, onDelete }: PacketPreviewProps) {
  const [editing, setEditing] = useState(false);
  const [packetText, setPacketText] = useState(() => generatePacketText(personName));

  const handleDownload = useCallback(() => {
    // Client-side PDF generation via hidden iframe print. No popup blocker issues.
    const iframe = document.createElement("iframe");
    iframe.style.position = "fixed";
    iframe.style.right = "0";
    iframe.style.bottom = "0";
    iframe.style.width = "0";
    iframe.style.height = "0";
    iframe.style.border = "none";
    document.body.appendChild(iframe);

    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!doc) {
      announce("Could not generate packet. Please try again.");
      document.body.removeChild(iframe);
      return;
    }

    doc.open();
    doc.write(`
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>RealDoor Readiness Packet</title>
        <style>
          body { font-family: "Inter", Arial, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 24px; color: #1C2B33; line-height: 1.7; }
          h1 { font-family: Georgia, serif; color: #1F5C5A; font-size: 1.8rem; margin-bottom: 4px; }
          .subtitle { color: #6C7680; font-size: 0.9rem; margin-bottom: 32px; }
          .section { margin-bottom: 24px; padding: 16px; border: 1px solid #DED6C6; border-radius: 8px; }
          .section h2 { font-size: 1rem; color: #1F5C5A; margin: 0 0 8px; }
          .field { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #ECE6D8; }
          .field:last-child { border-bottom: none; }
          .label { color: #6C7680; font-size: 0.85rem; }
          .value { font-weight: 700; font-size: 0.9rem; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #DED6C6; color: #6C7680; font-size: 0.78rem; text-align: center; }
          .notice { background: #ECE6D8; padding: 12px 16px; border-radius: 8px; color: #1F5C5A; font-weight: 700; font-size: 0.85rem; text-align: center; margin-top: 24px; }
        </style>
      </head>
      <body>
        <h1>RealDoor Readiness Packet</h1>
        <p class="subtitle">Prepared for ${personName} &middot; ${new Date().toISOString().split("T")[0]}</p>
        <div class="section">
          <h2>Confirmed Profile</h2>
          <div class="field"><span class="label">Monthly gross income</span><span class="value">Confirmed by renter</span></div>
          <div class="field"><span class="label">Household size</span><span class="value">3 people</span></div>
          <div class="field"><span class="label">Program</span><span class="value">Harbor View Homes &ndash; LIHTC (2026)</span></div>
        </div>
        <div class="section">
          <h2>Calculation Summary</h2>
          <div class="field"><span class="label">Formula</span><span class="value">Monthly gross income &times; 12</span></div>
          <div class="field"><span class="label">Effective date</span><span class="value">2026-04-01</span></div>
          <div class="field"><span class="label">Source</span><span class="value">Harbor View Homes &ndash; LIHTC income limits (2026)</span></div>
          <div class="field"><span class="label">Computed by</span><span class="value">The rule engine, not the AI</span></div>
        </div>
        <div class="section">
          <h2>Document Checklist</h2>
          <div class="field"><span class="label">Recent pay stub</span><span class="value">&check; Present</span></div>
          <div class="field"><span class="label">Photo identification</span><span class="value">&cross; Missing</span></div>
          <div class="field"><span class="label">Benefit letter</span><span class="value">&#9888; Expired (03/2026)</span></div>
        </div>
        <div class="notice">RealDoor never sends this for you. You decide where it goes.</div>
        <div class="footer">
          <p>A qualified person makes the decision. This packet is informational only.</p>
          <p>Generated by RealDoor &middot; AI assisted. Human approved.</p>
        </div>
      </body>
      </html>
    `);
    doc.close();

    setTimeout(() => {
      iframe.contentWindow?.print();
      setTimeout(() => { document.body.removeChild(iframe); }, 1000);
    }, 300);
    announce("Packet ready to save as PDF.");
  }, [personName, announce]);

  const handleDelete = useCallback(() => {
    onDelete();
    announce("Packet deleted. Session data cleared.");
  }, [onDelete, announce]);

  const handleEdit = useCallback(() => {
    setEditing(true);
    announce("Packet is now editable.");
  }, [announce]);

  const handleDoneEditing = useCallback(() => {
    setEditing(false);
    announce("Edits saved to packet.");
  }, [announce]);

  return (
    <div className="packet-preview">
      <p className="mono panel-kicker">Your readiness packet</p>
      <h3 className="packet-title">
        {ready ? "Packet ready for review" : "Complete the profile to build a packet"}
      </h3>

      {ready && (
        <div className="packet-content">
          <div className="packet-text-preview">
            {editing ? (
              <textarea
                className="packet-textarea"
                value={packetText}
                onChange={(e) => setPacketText(e.target.value)}
                aria-label="Edit packet contents"
                rows={10}
              />
            ) : (
              <pre className="packet-text-readonly" aria-label="Packet preview">
                {packetText}
              </pre>
            )}
          </div>

          <div className="packet-actions">
            {editing ? (
              <button className="secondary" type="button" onClick={handleDoneEditing}>
                Done editing
              </button>
            ) : (
              <button className="text-control" type="button" onClick={handleEdit}>
                Edit packet
              </button>
            )}
            <button className="primary" type="button" onClick={handleDownload}>
              Download packet
            </button>
            <button className="secondary" type="button" onClick={handleDelete}>
              Delete packet
            </button>
          </div>
        </div>
      )}

      <p className="packet-notice">
        RealDoor never sends this for you. You decide where it goes.
      </p>
    </div>
  );
}
